services:
  uxrce:
    image: "dennis:uxrce"
    network_mode: "host"
  rosbridge:
    image: "dexi-docker:rosbridge"
    network_mode: "host"
  webtools:
    image: "dexi-docker:webtools"
    network_mode: "host"
    
