services:
  dashboard:
    build:
      dockerfile: Dockerfile_dashboard
    ports:
      - "80:80"
  ttyd:
    image: "tsl0922/ttyd"
    ports:
      - "7681:7681"
  code-server:
    image: "codercom/code-server:latest"
    ports:
      - "8081:8080"
  droneblocks:
    build:
      dockerfile: Dockerfile_droneblocks
    ports:
      - "7777:80"
  web-tools:
    build:
      dockerfile: Dockerfile_webtools
    ports:
      - "7778:80"