services:
  uxrce:
    image: "dennis:uxrce"
    ports:
     - "8888:8888/udp"
  rosbridge:
    image: "dexi-docker:rosbridge"
    ports:
     - "9090:9090"
  webtools:
    image: "dexi-docker:webtools"
    ports:
     - "7777:80"
    
